version: 2

project_name: filetug

before:
  hooks:
    - go mod tidy

builds:
  - id: filetug-unix
    main: .
    binary: filetug
    env: [ CGO_ENABLED=0 ]
    goos: [ linux, darwin ]
    goarch: [ amd64, arm64 ]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

  - id: filetug-windows
    main: .
    binary: filetug
    env: [ CGO_ENABLED=0 ]
    goos: [ windows ]
    goarch: [ amd64 ]
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: tarball
    formats: [ tar.gz ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ filetug-unix ]
    files:
      - README.md
      - LICENSE*

  - id: zip
    formats: [ zip ]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    ids: [ filetug-windows ]

checksum:
  name_template: checksums.txt

release:
  github:
    owner: datatug
    name: filetug

brews:
  #  Warning: brews is being phased out in favor of homebrew_casks
  #  •	GoReleaser warns that brews is being phased out
  #  •	But the replacement is not functionally equivalent yet
  #  •	CLI tools must use install + test
  #  •	homebrew_casks is designed for .app bundles, not CLIs
  #  So the only valid configuration right now is:
  #    👉 Keep using brews and ignore the warning
  - name: filetug
    ids:
      - tarball

    description: "FileTug – modern CLI file browser/picker with neat UI"
    homepage: https://github.com/filetug/filetug
    license: MIT

    repository:
      owner: datatug
      name: homebrew-filetug
      token: "{{ .Env.HOMEBREW_FILETUG_GITHUB_TOKEN }}"

    install: |
      bin.install "filetug"
      bin.install_symlink "filetug" => "ft"

    test: |
      system "#{bin}/filetug", "--version"
      system "#{bin}/ft", "--version"