// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/sneatv/tabs_app.go
//
// Generated by this command:
//
//	mockgen -source=pkg/sneatv/tabs_app.go -destination=pkg/sneatv/tabs_app_mock.go -package=sneatv
//

// Package sneatv is a generated GoMock package.
package sneatv

import (
	reflect "reflect"

	tview "github.com/rivo/tview"
	gomock "go.uber.org/mock/gomock"
)

// MockTabsApp is a mock of TabsApp interface.
type MockTabsApp struct {
	ctrl     *gomock.Controller
	recorder *MockTabsAppMockRecorder
	isgomock struct{}
}

// MockTabsAppMockRecorder is the mock recorder for MockTabsApp.
type MockTabsAppMockRecorder struct {
	mock *MockTabsApp
}

// NewMockTabsApp creates a new mock instance.
func NewMockTabsApp(ctrl *gomock.Controller) *MockTabsApp {
	mock := &MockTabsApp{ctrl: ctrl}
	mock.recorder = &MockTabsAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTabsApp) EXPECT() *MockTabsAppMockRecorder {
	return m.recorder
}

// QueueUpdateDraw mocks base method.
func (m *MockTabsApp) QueueUpdateDraw(f func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueUpdateDraw", f)
}

// QueueUpdateDraw indicates an expected call of QueueUpdateDraw.
func (mr *MockTabsAppMockRecorder) QueueUpdateDraw(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueUpdateDraw", reflect.TypeOf((*MockTabsApp)(nil).QueueUpdateDraw), f)
}

// SetFocus mocks base method.
func (m *MockTabsApp) SetFocus(p tview.Primitive) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFocus", p)
}

// SetFocus indicates an expected call of SetFocus.
func (mr *MockTabsAppMockRecorder) SetFocus(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocus", reflect.TypeOf((*MockTabsApp)(nil).SetFocus), p)
}
