// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/filetug/navigator/app.go
//
// Generated by this command:
//
//	mockgen -source=pkg/filetug/navigator/app.go -destination=pkg/filetug/navigator/app_mock.go -package=navigator
//

// Package navigator is a generated GoMock package.
package tviewmocks

import (
	reflect "reflect"

	tview "github.com/rivo/tview"
	gomock "go.uber.org/mock/gomock"
)

// MockApp is a mock of App interface.
type MockApp struct {
	ctrl     *gomock.Controller
	recorder *MockAppMockRecorder
	isgomock struct{}
}

// MockAppMockRecorder is the mock recorder for MockApp.
type MockAppMockRecorder struct {
	mock *MockApp
}

// NewMockApp creates a new mock instance.
func NewMockApp(ctrl *gomock.Controller) *MockApp {
	mock := &MockApp{ctrl: ctrl}
	mock.recorder = &MockAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApp) EXPECT() *MockAppMockRecorder {
	return m.recorder
}

// EnableMouse mocks base method.
func (m *MockApp) EnableMouse(arg0 bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "EnableMouse", arg0)
}

// EnableMouse indicates an expected call of EnableMouse.
func (mr *MockAppMockRecorder) EnableMouse(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnableMouse", reflect.TypeOf((*MockApp)(nil).EnableMouse), arg0)
}

// QueueUpdateDraw mocks base method.
func (m *MockApp) QueueUpdateDraw(f func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueUpdateDraw", f)
}

// QueueUpdateDraw indicates an expected call of QueueUpdateDraw.
func (mr *MockAppMockRecorder) QueueUpdateDraw(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueUpdateDraw", reflect.TypeOf((*MockApp)(nil).QueueUpdateDraw), f)
}

// Run mocks base method.
func (m *MockApp) Run() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run")
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockAppMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockApp)(nil).Run))
}

// SetFocus mocks base method.
func (m *MockApp) SetFocus(p tview.Primitive) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFocus", p)
}

// SetFocus indicates an expected call of SetFocus.
func (mr *MockAppMockRecorder) SetFocus(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocus", reflect.TypeOf((*MockApp)(nil).SetFocus), p)
}

// SetRoot mocks base method.
func (m *MockApp) SetRoot(root tview.Primitive, fullscreen bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRoot", root, fullscreen)
}

// SetRoot indicates an expected call of SetRoot.
func (mr *MockAppMockRecorder) SetRoot(root, fullscreen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRoot", reflect.TypeOf((*MockApp)(nil).SetRoot), root, fullscreen)
}

// Stop mocks base method.
func (m *MockApp) Stop() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop")
}

// Stop indicates an expected call of Stop.
func (mr *MockAppMockRecorder) Stop() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockApp)(nil).Stop))
}
