// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/rivo/tview (interfaces: Primitive)
//
// Generated by this command:
//
//	mockgen -destination=pkg/filetug/tview_mock_test.go -package=filetug github.com/rivo/tview Primitive
//

// Package filetug is a generated GoMock package.
package tviewmocks

import (
	reflect "reflect"

	tcell "github.com/gdamore/tcell/v2"
	tview "github.com/rivo/tview"
	gomock "go.uber.org/mock/gomock"
)

// MockPrimitive is a mock of Primitive interface.
type MockPrimitive struct {
	ctrl     *gomock.Controller
	recorder *MockPrimitiveMockRecorder
	isgomock struct{}
}

// MockPrimitiveMockRecorder is the mock recorder for MockPrimitive.
type MockPrimitiveMockRecorder struct {
	mock *MockPrimitive
}

// NewMockPrimitive creates a new mock instance.
func NewMockPrimitive(ctrl *gomock.Controller) *MockPrimitive {
	mock := &MockPrimitive{ctrl: ctrl}
	mock.recorder = &MockPrimitiveMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPrimitive) EXPECT() *MockPrimitiveMockRecorder {
	return m.recorder
}

// Blur mocks base method.
func (m *MockPrimitive) Blur() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Blur")
}

// Blur indicates an expected call of Blur.
func (mr *MockPrimitiveMockRecorder) Blur() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Blur", reflect.TypeOf((*MockPrimitive)(nil).Blur))
}

// Draw mocks base method.
func (m *MockPrimitive) Draw(screen tcell.Screen) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Draw", screen)
}

// Draw indicates an expected call of Draw.
func (mr *MockPrimitiveMockRecorder) Draw(screen any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Draw", reflect.TypeOf((*MockPrimitive)(nil).Draw), screen)
}

// Focus mocks base method.
func (m *MockPrimitive) Focus(delegate func(tview.Primitive)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Focus", delegate)
}

// Focus indicates an expected call of Focus.
func (mr *MockPrimitiveMockRecorder) Focus(delegate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Focus", reflect.TypeOf((*MockPrimitive)(nil).Focus), delegate)
}

// GetRect mocks base method.
func (m *MockPrimitive) GetRect() (int, int, int, int) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRect")
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(int)
	ret3, _ := ret[3].(int)
	return ret0, ret1, ret2, ret3
}

// GetRect indicates an expected call of GetRect.
func (mr *MockPrimitiveMockRecorder) GetRect() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRect", reflect.TypeOf((*MockPrimitive)(nil).GetRect))
}

// HasFocus mocks base method.
func (m *MockPrimitive) HasFocus() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasFocus")
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasFocus indicates an expected call of HasFocus.
func (mr *MockPrimitiveMockRecorder) HasFocus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasFocus", reflect.TypeOf((*MockPrimitive)(nil).HasFocus))
}

// InputHandler mocks base method.
func (m *MockPrimitive) InputHandler() func(*tcell.EventKey, func(tview.Primitive)) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InputHandler")
	ret0, _ := ret[0].(func(*tcell.EventKey, func(tview.Primitive)))
	return ret0
}

// InputHandler indicates an expected call of InputHandler.
func (mr *MockPrimitiveMockRecorder) InputHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InputHandler", reflect.TypeOf((*MockPrimitive)(nil).InputHandler))
}

// MouseHandler mocks base method.
func (m *MockPrimitive) MouseHandler() func(tview.MouseAction, *tcell.EventMouse, func(tview.Primitive)) (bool, tview.Primitive) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MouseHandler")
	ret0, _ := ret[0].(func(tview.MouseAction, *tcell.EventMouse, func(tview.Primitive)) (bool, tview.Primitive))
	return ret0
}

// MouseHandler indicates an expected call of MouseHandler.
func (mr *MockPrimitiveMockRecorder) MouseHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MouseHandler", reflect.TypeOf((*MockPrimitive)(nil).MouseHandler))
}

// PasteHandler mocks base method.
func (m *MockPrimitive) PasteHandler() func(string, func(tview.Primitive)) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PasteHandler")
	ret0, _ := ret[0].(func(string, func(tview.Primitive)))
	return ret0
}

// PasteHandler indicates an expected call of PasteHandler.
func (mr *MockPrimitiveMockRecorder) PasteHandler() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PasteHandler", reflect.TypeOf((*MockPrimitive)(nil).PasteHandler))
}

// SetRect mocks base method.
func (m *MockPrimitive) SetRect(x, y, width, height int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRect", x, y, width, height)
}

// SetRect indicates an expected call of SetRect.
func (mr *MockPrimitiveMockRecorder) SetRect(x, y, width, height any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRect", reflect.TypeOf((*MockPrimitive)(nil).SetRect), x, y, width, height)
}
