// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/viewers/dir_previewer_app.go
//
// Generated by this command:
//
//	mockgen -source=pkg/viewers/dir_previewer_app.go -destination=pkg/viewers/dir_previewer_app_mock.go -package=viewers
//

// Package viewers is a generated GoMock package.
package viewers

import (
	reflect "reflect"

	tview "github.com/rivo/tview"
	gomock "go.uber.org/mock/gomock"
)

// MockDirPreviewerApp is a mock of DirPreviewerApp interface.
type MockDirPreviewerApp struct {
	ctrl     *gomock.Controller
	recorder *MockDirPreviewerAppMockRecorder
	isgomock struct{}
}

// MockDirPreviewerAppMockRecorder is the mock recorder for MockDirPreviewerApp.
type MockDirPreviewerAppMockRecorder struct {
	mock *MockDirPreviewerApp
}

// NewMockDirPreviewerApp creates a new mock instance.
func NewMockDirPreviewerApp(ctrl *gomock.Controller) *MockDirPreviewerApp {
	mock := &MockDirPreviewerApp{ctrl: ctrl}
	mock.recorder = &MockDirPreviewerAppMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDirPreviewerApp) EXPECT() *MockDirPreviewerAppMockRecorder {
	return m.recorder
}

// QueueUpdateDraw mocks base method.
func (m *MockDirPreviewerApp) QueueUpdateDraw(f func()) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "QueueUpdateDraw", f)
}

// QueueUpdateDraw indicates an expected call of QueueUpdateDraw.
func (mr *MockDirPreviewerAppMockRecorder) QueueUpdateDraw(f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "QueueUpdateDraw", reflect.TypeOf((*MockDirPreviewerApp)(nil).QueueUpdateDraw), f)
}

// SetFocus mocks base method.
func (m *MockDirPreviewerApp) SetFocus(p tview.Primitive) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetFocus", p)
}

// SetFocus indicates an expected call of SetFocus.
func (mr *MockDirPreviewerAppMockRecorder) SetFocus(p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetFocus", reflect.TypeOf((*MockDirPreviewerApp)(nil).SetFocus), p)
}
