// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/viewers/previewer.go
//
// Generated by this command:
//
//	mockgen -source=pkg/viewers/previewer.go -destination=pkg/viewers/previewer_mock.go -package=viewers
//

// Package viewers is a generated GoMock package.
package viewers

import (
	reflect "reflect"

	files "github.com/filetug/filetug/pkg/files"
	tview "github.com/rivo/tview"
	gomock "go.uber.org/mock/gomock"
)

// MockPreviewer is a mock of Previewer interface.
type MockPreviewer struct {
	ctrl     *gomock.Controller
	recorder *MockPreviewerMockRecorder
	isgomock struct{}
}

// MockPreviewerMockRecorder is the mock recorder for MockPreviewer.
type MockPreviewerMockRecorder struct {
	mock *MockPreviewer
}

// NewMockPreviewer creates a new mock instance.
func NewMockPreviewer(ctrl *gomock.Controller) *MockPreviewer {
	mock := &MockPreviewer{ctrl: ctrl}
	mock.recorder = &MockPreviewerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPreviewer) EXPECT() *MockPreviewerMockRecorder {
	return m.recorder
}

// Main mocks base method.
func (m *MockPreviewer) Main() tview.Primitive {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Main")
	ret0, _ := ret[0].(tview.Primitive)
	return ret0
}

// Main indicates an expected call of Main.
func (mr *MockPreviewerMockRecorder) Main() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Main", reflect.TypeOf((*MockPreviewer)(nil).Main))
}

// Meta mocks base method.
func (m *MockPreviewer) Meta() tview.Primitive {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Meta")
	ret0, _ := ret[0].(tview.Primitive)
	return ret0
}

// Meta indicates an expected call of Meta.
func (mr *MockPreviewerMockRecorder) Meta() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Meta", reflect.TypeOf((*MockPreviewer)(nil).Meta))
}

// PreviewSingle mocks base method.
func (m *MockPreviewer) PreviewSingle(entry files.EntryWithDirPath, data []byte, dataErr error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PreviewSingle", entry, data, dataErr)
}

// PreviewSingle indicates an expected call of PreviewSingle.
func (mr *MockPreviewerMockRecorder) PreviewSingle(entry, data, dataErr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreviewSingle", reflect.TypeOf((*MockPreviewer)(nil).PreviewSingle), entry, data, dataErr)
}
